name: C++ CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Cpp (C++ / C)
        uses: aminya/setup-cpp@v0.37.0
        with:
          compiler: gcc-11
          cmake: true
          make: true
          
      - name: Build project
        run: make
          
      - name: Run tests
        run: make test
        
      - name: Run siege test
        run: |
          cd siegetest
          # Add command to run siege test here
          # For example: siege -c 100 -t 1M http://localhost:8080
        
      - name: Lint code
        run: |
          # Add linting steps here if you have any
          # For example: cppcheck src/
          
      - name: Check formatting
        run: |
          # Add formatting check here if you use a formatter
          # For example: clang-format --dry-run --Werror src/**/*.cpp src/**/*.h
